# NumPy Ejercicios

#### Importar librería



In [1]:
import numpy as np 

#### Crear una array (unidimensional) con 10 ceros

In [2]:
array_ceros= np.zeros(10)
print(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Resultado esperado:
```python
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```

#### Crear un array (unidimensional) con 10 unos

In [3]:
array_unos= np.ones(10)
print(array_unos)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Resultado esperado:
```python
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

#### Crear un array con 10 cincos

In [4]:
array_cincos= np.full((10),5)
print(array_cincos)

[5 5 5 5 5 5 5 5 5 5]


Resultado esperado:
```python
array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])
```

#### Crear un array (unidimensional) con los números enteros desde 10 hasta 50

In [5]:
array_random= np.arange(10,51)
print(array_random)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Resultado esperado:
```python
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])
```

#### Crear un array (unidimensional) con los enteros pares comprendidos entre 10 y 50

In [6]:
array_random2= np.arange(10,51,2)
print(array_random2)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Resultado esperado:
```python
array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])
```

#### Crear una matriz 3x3 con los enteros comprendidos entre 0 y 8

In [7]:
matriz33= np.arange(9).reshape(3,3)
print(matriz33)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Resultado esperado:
```python
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

#### Crear una matriz identidad de orden 3

In [8]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Resultado esperado:
```python
array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])
```

#### Generar un número aleatorio proveniente de una distribución uniforme, entre 0 y 1

In [9]:
aleatorio = np.random.rand()
print(aleatorio)

0.5643287549993123


#### Obtener 25 números aleatorios procedentes de una distribución normal estandar

In [10]:
array25 = np.random.randn(25)
print(array25)

[ 1.01203145 -0.01419577 -1.38007383  0.37753824 -0.9670258  -1.34540861
 -0.28840971  0.44826764  1.64801587  1.87308586 -1.69927053  0.96711357
  1.07084505 -1.22660232 -0.65882405  2.54352276 -0.0304507  -1.40500007
  0.83987054  2.31684742 -1.26919237 -0.57908303 -1.14002291  0.38773987
 -0.74379723]


#### Genera la siguiente matriz:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

In [11]:
array100 = np.arange(0.01,1.01,0.01).reshape(10,10)
#np.random.randn(100).reshape(10,10)
print(array100)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Crear un vector de 20 valores equidistantes entre 0 y 1

In [12]:
vector=np.linspace(0,1,20)
print(vector)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


Resultado esperado:
```python
array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])
```

## Numpy Indexado y filtrado

Dada la siguiente matriz, realice las operaciones pertinentes para obtener la salida que se pide:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Primer ejercicio**

In [14]:
submatriz = mat[2:5, 1:5]
print(submatriz)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


*Resultado esperado:*


```
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```



**Segundo ejercicio**

In [15]:
print(mat[3,4])

20


*Resultado esperado:*

```
20
```



**Tercer ejercicio**

In [16]:
submatriz2 = mat[0:3, 1:2]
print(submatriz2)

[[ 2]
 [ 7]
 [12]]


*Resultado esperado:*

```
array([[ 2],
       [ 7],
       [12]])
```



**Cuarto ejercicio**

In [17]:
submatriz3 = mat[-1:, :]
print(submatriz3)

[[21 22 23 24 25]]


*Resultado esperado:*


```
array([21, 22, 23, 24, 25])
```



**Quinto ejercicio**

In [18]:
submatriz3 = mat[-2:, :]
print(submatriz3)

[[16 17 18 19 20]
 [21 22 23 24 25]]


*Resultado esperado:*


```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```



### Realice los siguiente cálculos:

#### Obtenga la suma de todos los valores de la matriz

In [19]:
print(np.sum(mat))

325


*Resultado esperado:*


```python
325
```

#### Calcule la desviación típica de los valores de la matriz

In [20]:
np.std(mat)

np.float64(7.211102550927978)

*Resultado esperado:*


```python
7.211102550927978
```

#### Sume los valores por columnas



In [21]:
print(np.sum(mat, axis=0))

[55 60 65 70 75]


*Resultado esperado:*


```python
array([55, 60, 65, 70, 75])
```

##Avanzado

###Obtenga el rango de la siguiente matriz cuadrada:

```python
Z = np.random.uniform(0,1,(10,10))
```

*(Indicaciones: Al ser cuadrada, podemos analizar sus autovalores)*

In [ ]:
#Z = np.random.uniform(0,1,(10,10))
#U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
#rank = np.sum(S > 1e-10)
#print(rank)

###Implemente el algoritmo k-NN (*k Nearest Neighbours*)

*Indicaciones: Este algoritmo de aprendizaje supervisado consiste en asignar, a cada elemento, la media de las labels de los k vecinos más cercanos que tenga dicho elemento.*


*Veámoslo sobre un ejemplo: Supongamos que tenemos una serie de variables comportamentales de estudiantes (visualizaciones, ediciones, creaciones y descargas):*

```python
array([[19,  7, 12,  4],
       [19,  0,  7,  9],
       [17, 12, 17,  6],
       [ 8, 10,  1, 12],
       [ 9,  6,  0, 15],
       [11, 18,  1, 14],
       [16,  8, 12,  1],
       [ 2, 13,  6, 17],
       [ 0,  7, 13,  8],
       [15,  9, 10, 15]])
```

*Asociado a estos datos, tenemos además una calificación del estudiante a final de curso:*

```python
array([[6],
       [4],
       [7],
       [4],
       [3],
       [9],
       [9],
       [5],
       [3],
       [4]])
```

*A los datos que usamos para tratar de estimar las calificaciones los llamaremos features, y a la nota en sí la label del problema. Cada fila es el registro de un alumno, por lo que entendemos que la información de los estudiantes la podemos representar en un espacio 4-dimensional.*

*Bajo estas circunstancias, el algoritmo sigue estos pasos:*

1.  *Para un cierto estudiante sin calificación, calculamos la distancia (en el mencionado espacio 4-dimensional) del estudiante sin calificar a cada uno de los calificados.*

2.  *Habiendo prefijado el parámetro k, escogemos las notas de los k estudiantes más cercanos.*

3.  *Hacemos la media (moda en caso discreto) de estos datos, y esa será la estimación que tengamos del alumno.*


In [22]:
#Creamos función que, dados dos arrays 1D, nos devuelva la distancia euclídea de los mismos
def euclidean_distance(vec1, vec2):
  #Algunas comprobaciones para mejorar la búsqueda de errores en código son:
  #if (type(vec1)!=np.ndarray) | (type(vec2)!=np.ndarray):
  # raise ValueError('El formato de alguno de los vectores de entrada no es np.array.')
  #if vec1.shape!=vec2.shape:
  # raise ValueError('Los arrays de entrada no tienen la misma forma.')
  return np.sqrt(np.sum((vec1-vec2)**2, axis = -1))

In [23]:
#Fijamos número de "vecinos" en los que basar la nota
k = 2

#Obtenemos features
features = np.array([[19,  7, 12,  4],
                     [19,  0,  7,  9],
                     [17, 12, 17,  6],
                     [ 8, 10,  1, 12],
                     [ 9,  6,  0, 15],
                     [11, 18,  1, 14],
                     [16,  8, 12,  1],
                     [ 2, 13,  6, 17],
                     [ 0,  7, 13,  8],
                     [15,  9, 10, 15]])

#Obtenemos label
label = np.array([[6],[4],[7],[4],[3],[9],[9],[5],[3],[4]])

#Fijamos un alumno nuevo
new_student = np.array([15, 6, 5, 2])

#Calculamos distancias
distances = np.zeros(label.shape) #Inicializamos un array para contener las distancias
for i in np.arange(label.shape[0]):
  distances[i] = euclidean_distance(features[i,:], new_student)

#Obtenemos los índices de los k vecinos más próximos
optimal_idx = np.argpartition(distances.reshape(-1), k)[:k]

#Mostramos resultado
label_new_student = np.round(np.mean(label[optimal_idx]),2)
print('La predicción para el nuevo estudiante es: {}'.format(label_new_student))

La predicción para el nuevo estudiante es: 7.5
